export const wordList = [
            {a: "AĞAÇ", m: "gövdesi odun olan bitki."}, {a: "ALTIN", m: "değerli sarı maden."}, {a: "ANNE", m: "Cennetin ayaklarının altında olduğu müjdelenen kişi."}, {a: "ARABA", m: "4 tekerlekli genellikle üstü kapalı olan taşıt."}, {a: "BALIK", m: "Nefes almak için suya muhtaç olan canlı."}, {a: "BEBEK", m: "Ailenin Yeni üyesi"}, {a: "BEYİN", m: "sinir sisteminin merkezi."}, {a: "BİLGİ", m: "Öğrenilen her şeyin toplamı, başarının anahtarı."}, {a: "BULUT", m: "Gökyüzünde görülen su damlacıklarından oluşan küme."}, {a: "ÇANTA", m: "İçine eşya konur elde ya da omuzda taşınır."}, {a: "ÇİÇEK", m: "Bitkilerin üreme organı olan kısım."}, {a: "ÇOCUK", m: "henüz büyüyememiş birey"}, {a: "DENİZ", m: "geniş tuzlu su kütlesi."}, {a: "DEFTER", m: "Bilgilerin düzenli şekilde tutulduğu kağıtlar bütünü."}, {a: "DOST", m: "Bağ kurulan samimi insan"}, {a: "DUVAR", m: "Mekanları sınırlandıran sabit yapı öğesi."}, {a: "ELMA", m: "Kırmızı yeşil ya da sarı olabilen tatlı bir meyve."}, {a: "EV", m: "Günlük hayatın geçtiği yaşam alanı."}, {a: "FENER", m: "pil ile çalışan aydınlatma aracı."}, {a: "GEMİ", m: "Uzun yolculuklar yapan büyük su taşıtı"}, {a: "GÖZ", m: "görme organı."}, {a: "GÜNEŞ", m: "dünyayı aydınlatan yıldız."}, {a: "HAYAT", m: "Doğumdan ölüme kadar geçen zaman."}, {a: "IRMAK", m: "Denize dökülen büyük akarsu."}, {a: "IŞIK", m: "görmeyi sağlayan enerji."}, {a: "KALEM", m: "Düşünceleri yazıya dökmeye yarayan araç."}, {a: "KAPI", m: "Giriş çıkışı sağlayan açılıp kapanan bölüm."}, {a: "KEDİ", m: "memeli hayvanlar sınıfına ait, küçük boyutlu, çevik ve etçil bir türdür."}, {a: "KİTAP", m: "Bilgi veya hikâye içeren basılı eser."}, {a: "KÖPRÜ", m: "iki yeri bağlayan yapı."}, {a: "KUŞ", m: "uçabilen hayvan."}, {a: "MASA", m: "üzerinde ders çalıştığımız mobilya."}, {a: "OKUL", m: "eğitim verilen yer."}, {a: "OYUN", m: "Yetenek ve zekâ geliştirici, belli kuralları olan, iyi vakit geçirmeye yarayan eğlence."}, {a: "PENCERE", m: "Işık ve hava girişi sağlayan açıklık."},{a: "SU", m: "yaşam için gerekli sıvı."}, {a: "TOP", m: "yuvarlak oyun aracı."}, {a: "UYKU", m: "dinlenme hali."}, {a: "YAZI", m: "harflerle anlatım."}, {a: "YILDIZ", m: "Gökyüzünde kendi ışığını yayarak parlayan gök cismi."}, {a: "YOL", m: "Ulaşım ve geçiş için kullanılan alan."}, {a: "KUM", m: "Deniz ve çöllerde bulunan çok küçük taş taneleri."},{a: "MUTFAK", m: "yemek yapılan yer."}, {a: "BİBER", m: "acı veya tatlı sebze."}, {a: "SAKIZ", m: "Çiğnenen ve ağızda dağılan esnek madde."}, {a: "ÇATI", m: "Bir yapının üstünü örten ve koruyan bölüm."}, {a: "YASTIK", m: "Uyurken başın altına konulan yumuşak eşya."}, {a: "KİRPİ", m: "dikenli küçük hayvan."}, {a: "OYUNCAK", m: "Çocukların oynaması için yapılan eşya."}, {a: "ÇAY", m: "Demlenerek hazırlanan sıcak içecek."}, {a: "GÖL", m: "Karalarla çevrili durgun su birikintisi."}, {a: "KART", m: "Alışveriş ve ödeme yapmaya yarayan plastik kart."}, {a: "MÜZİK", m: "İnsanları etkileyen ve zevk veren ses düzeni."}, {a: "SİNEK", m: "Havada dolaşan ve vızıldayan küçük haşere."}, {a: "BALON", m: "İçi hava veya gazla doldurulan hafif oyuncak."}, {a: "BÜYÜKADA", m: "istanbulda bir ada."}, {a: "MAYMUN", m: "İnsana benzeyen hareketleri olan kuyruklu memeli."}, {a: "HAVA", m: "yaşam için gerekli gaz."}, {a: "KÖPEK", m: "Evleri koruyan ve eğitilebilen hayvan."}, {a: "ÇORAP", m: "Ayağı sıcak tutmak için giyilen giysi."}, {a: "BİLGİSAYAR", m: "Bilgi işleyen ve saklayan elektronik cihaz."}, {a: "FOTOĞRAF", m: "resim veya görüntü kaydı."}, {a: "MOTOR", m: "Hareket üretmek için enerjiyi mekanik güce çeviren makine."}, {a: "ŞEMSİYE", m: "Yağmur ve güneşten korunmak için kullanılan açılır kapanır araç."}, {a: "LAMBA", m: "ışık veren aydınlatma aracı."}, {a: "BİYOLOJİ", m: "canlıları inceleyen bilim."}, {a: "TAVŞAN", m: "Hızlı koşan ve uzun kulaklı memeli hayvan."}, {a: "ŞEHİR", m: "İnsanların yoğun olarak yaşadığı yerleşim alanı."}, {a: "KUYRUK", m: "Bazı hayvanların arka kısmında bulunan uzantı."}, {a: "YUMURTA", m: "tavuk ve kuşların ürünü."}, {a: "BİBERON", m: "Emzik ve ağızdan beslenmeyi sağlayan kaplı araç."}, {a: "ÇÖP", m: "atık madde."}, {a: "MUTLULUK", m: "iyi hissetme durumu."}, {a: "GÖZLÜK", m: "görmeyi kolaylaştıran araç."}, {a: "ÇİZİM", m: "Kalem veya fırça ile yapılan resim veya tasarım."}, {a: "AYAKKABI", m: "ayak koruyucu giysi."}, {a: "TÜRKİYE", m: "81 ili olan ülke."}, {a: "BİRLİK", m: "bir araya gelme durumu."}, {a: "ÇORBA", m: "Sulu ve yiyeceklerle yapılan sıcak yemek."}, {a: "KUMANDA", m: "cihazı uzaktan kontrol eden eşya."}, {a: "KÖY", m: "küçük yerleşim yeri."}, {a: "KUAFÖR", m: "saç kesimi ve bakım hizmeti veren yer."}, {a: "PİZZA", m: "Üzerine peynir, sos ve malzeme konularak fırında pişirilen yiyecek."}, {a: "ŞEKER", m: "Tatlı ve genellikle küçük katı yiyecek."}, {a: "BAYRAK", m: "ülke simgesi."}, {a: "MÜZE", m: "eserlerin sergilendiği yer."}, {a: "TÜNEL", m: "yer altından geçen yol."}, {a: "KİLİT", m: "Kapıları veya eşyaları güvenli hale getiren araç."}, {a: "BANDANA", m: "Baş veya boyuna bağlanan ince kumaş parça."}, {a: "KAFES", m: "Hayvanları içinde tutmak için yapılan tel veya demirden yapı."}, {a: "YAY", m: "Esnek malzeme ile energy depolayan ve fırlatma aracı."}, {a: "ÇİMENTO", m: "Binalarda sağlamlık sağlamak için kullanılan toz malzeme"}, {a: "TRAFO", m: "Elektrik voltajını yükselten veya düşüren cihaz."}, {a: "FIRIN", m: "Isı ve ısıtma ile yiyecekleri pişiren mutfak aracı."}, {a: "RADYO", m: "ses ile bilgi veren cihaz."}, {a: "KABLO", m: "elektrik veya veri taşıyan tel."}, {a: "TELEFON", m: "Sesli ve yazılı iletişim kurmayı sağlayan cihaz."}, {a: "KASABA", m: "şehirden küçük yerleşim yeri."}, {a: "KAHVE", m: "Kavrulmuş çekirdeklerden hazırlanan sıcak içecek."}, {a: "BASKETBOL", m: "İki takımın topu potaya atarak sayı yaptığı spor oyunu."}, {a: "PASTANE", m: "tatlı ve yiyecek yapılan yer."}, {a: "TAVUK", m: "kümes hayvanı."}, {a: "KARTON", m: "kalın kağıt türü."}, {a: "GÜL", m: "çiçek türü."}, {a: "ADALET", m: "hak ve doğruluğa uygunluk."}, {a: "AKIL", m: "düşünme ve anlama yeteneği."}, {a: "ALARM", m: "uyarı veren sistem."}, {a: "AYNA", m: "yansıma sağlayan cam."}, {a: "BAHÇE", m: "bitki yetiştirilen alan."}, {a: "BANT", m: "yapıştırıcı şerit."}, {a: "BARDAK", m: "sıvı içmeye yarayan kap."}, {a: "BATTANİYE", m: "örtünmek için kullanılan kalın örtü."}, {a: "BİSİKLET", m: "pedallı iki tekerlekli araç."}, {a: "BORU", m: "sıvı veya gaz taşıyan kanal."}, {a: "BUZDOLABI", m: "yiyecekleri soğutan cihaz."}, {a: "CEKET", m: "üst vücuda giyilen giysi."}, {a: "CÜZDAN", m: "para ve kart konulan eşya."}, {a: "DERS", m: "öğrenme amacıyla yapılan etkinlik."}, {a: "DOLAP", m: "eşya saklanan mobilya."}, {a: "DÜĞME", m: "giysileri iliklemeye yarayan parça."}, {a: "EKRAN", m: "görüntü gösteren yüzey."}, {a: "ELDİVEN", m: "eli koruyan giysi."}, {a: "FATURA", m: "ödeme belgesi."}, {a: "FIRÇA", m: "temizlik veya boyama aracı."}, {a: "GARDIROP", m: "giysi dolabı."}, {a: "GÖMLEK", m: "üst vücuda giyilen kıyafet."}, {a: "HALI", m: "zemine serilen eşya."}, {a: "HOPARLÖR", m: "ses çıkaran cihaz."}, {a: "İLAÇ", m: "hastalık tedavisinde kullanılan madde."}, {a: "İPEK", m: "böcekten elde edilen ince lif."}, {a: "KAĞIT", m: "yazı yazmaya yarayan yüzey."}, {a: "KASK", m: "baş koruyucu ekipman."}, {a: "KETÇAP", m: "domatesten yapılan sos."}, {a: "KLAVYE", m: "yazı girişi yapılan tuş takımı."}, {a: "KOLTUK", m: "oturmak için kullanılan eşya."}, {a: "KREM", m: "cilt bakım ürünü."}, {a: "LİMON", m: "ekşi bir meyve."}, {a: "LOKMA", m: "küçük yiyecek parçası."}, {a: "MANDAL", m: "çamaşır tutturma aracı."}, {a: "MERDİVEN", m: "katlar arası geçiş yapısı."}, {a: "MİKROFON", m: "ses kaydetme aracı."}, {a: "MONİTÖR", m: "bilgisayar görüntü birimi."}, {a: "NALBUR", m: "yapı malzemesi satan yer."}, {a: "NOT", m: "kısa yazılı hatırlatma."}, {a: "OBJEKTİF", m: "fotoğraf makinesi parçası."}, {a: "ORGAN", m: "canlı vücudu parçası."}, {a: "OTOBÜS", m: "toplu taşıma aracı."}, {a: "PANO", m: "bilgi asılan yüzey."}, {a: "PANTOLON", m: "alt vücuda giyilen giysi."}, {a: "PİL", m: "taşınabilir enerji kaynağı."}, {a: "PRİZ", m: "elektrik bağlantı noktası."}, {a: "RAF", m: "eşya koyma bölmesi."}, {a: "SANDALYE", m: "oturmak için kullanılan eşya."}, {a: "SÜPÜRGE", m: "temizlik aracı."}, {a: "TABAK", m: "Yemek koymaya yarayan mutfak eşyası"}, {a: "TAKVİM", m: "günleri gösteren çizelge."}, {a: "TERLİK", m: "ev içinde giyilen ayakkabı."}, {a: "TİŞÖRT", m: "kısa kollu üst giysi."}, {a: "TORBA", m: "eşya taşıma aracı."}, {a: "TRAFİK", m: "araç ve yaya yoğunluğu."}, {a: "UÇAK", m: "havada yolculuk aracı."}, {a: "ÜTÜ", m: "Kıyafetlerdeki kırışıklıkları gidermeye yarayan alet."}, {a: "VİTRİN", m: "ürün sergilenen camlı alan."}, {a: "YEMEK", m: "beslenme amacıyla tüketilen şey."}, {a: "YOĞURT", m: "Sütün mayalanmasıyla elde edilen koyu kıvamlı ekşi tatlı bir süt ürünüdür"}, {a: "ZARF", m: "mektup konulan kağıt."},{a: "AKREP", m: "Zehrli sokma özelliği olan küçük hayvan."},
{a: "ARMUT", m: "Tatlı ve sulu meyve."},
{a: "AT", m: "İnsan veya yük taşımada kullanılan hızlı hayvan."},
{a: "AYI", m: "Büyük ve güçlü memeli hayvan."},
{a: "BÖCEK", m: "Küçük ve çok bacaklı omurgasız canlı."},
{a: "ÇİTA", m: "Dünyanın en hızlı kara hayvanı."},
{a: "DENİZYILDIZI", m: "Denizlerde yaşayan beş kollu canlı."},
{a: "FOK", m: "Suda yaşayan memeli hayvan."},
{a: "GEYİK", m: "Boynuzlu orman hayvanı."},
{a: "HIRSIZ", m: "Başkasının malını çalan kişi."},
{a: "İNEK", m: "Süt veren çiftlik hayvanı."},
{a: "JEL", m: "Yarı sıvı kıvamında madde."},
{a: "KAKTÜS", m: "Sulu ve dikenli bitki."},
{a: "LAPA", m: "Yoğun kar veya çamur birikintisi."},
{a: "MANGO", m: "Tropikal ve tatlı meyve."},
{a: "NEKTAR", m: "Çiçeklerden toplanan tatlı sıvı."},
{a: "OBJE", m: "Belirli amaçla kullanılan nesne."},
{a: "PANDA", m: "Siyah beyaz ve bambu yiyen hayvan."},
{a: "RAPOR", m: "Olay veya durum hakkında yazılı bilgi."},
{a: "SAL", m: "Küçük ve açık su aracı."},
{a: "TAVSİYE", m: "Bir konuda yol gösteren öneri."},
{a: "UĞURBÖCEĞİ", m: "Küçük ve kırmızı benekli böcek."},
{a: "VİYOLA", m: "Keman ailesinden yaylı çalgı."},
{a: "YELKENCİ", m: "Yelkenli tekne ile seyahat eden kişi."},
{a: "ZEBRA", m: "Çizgili ve otçul hayvan."},
{a: "AMBAR", m: "Eşya veya mal depolanan büyük yer."},
{a: "BİLGİSAYARCI", m: "Bilgisayar ile çalışan kişi."},
{a: "CİVCİV", m: "Yeni doğmuş tavuk."},
{a: "DİKİŞ", m: "İplik ile yapılan birleştirme işlemi."},
{a: "ELBİSE", m: "Vücut için giyilen giysi."},
{a: "FOSFOR", m: "Işığı yansıtan kimyasal element."},
{a: "GÖLGE", m: "Işığın engellenmesi ile oluşan karanlık alan."},
{a: "HIRS", m: "Fazla arzu veya tamah."},
{a: "ISITICI", m: "Alanı veya nesneyi ısıtan cihaz."},
{a: "JAPON", m: "Japonya vatandaşına denir."},
{a: "KİLOMETRE", m: "Uzunluk ölçü birimi."},
{a: "LİSANSLI", m: "Resmî izin veya belgeye sahip."},
{a: "MÜREKKEP", m: "Yazı yazmak için kullanılan sıvı boya."},
{a: "NELER", m: "Soru zamiri."},
{a: "ORTAOKUL", m: "İlkokuldan sonra öğrenim verilen kurum."},
{a: "PİYANO", m: "Tuşlu ve yaylı çalgı."},
{a: "RAFİNERİ", m: "Ham petrol işlenen fabrika."},
{a: "SOKAK", m: "Binalar arasında geçen yol."},
{a: "TOPLANTI", m: "Bir amaç için insanların bir araya gelmesi."},
{a: "ULUS", m: "Ortak kültür ve dili olan insanlar topluluğu."},
{a: "VİRAJ", m: "Yolun dönemeçli kısmı."},
{a: "YEL", m: "Hareket eden hava."},
{a: "ZİNCİR", m: "Halka halkaya bağlı metal parça."},
{a: "AÇIKHAVA", m: "Kapalı olmayan dış mekan."},
{a: "BİTKİ", m: "Toprakta büyüyen canlı organizma."},
{a: "ÇİZİK", m: "Yüzeyde oluşan ince çizgi veya hasar."}, {a: "EJDERHA", m: "Masallarda ağzından ateş çıkaran dev yaratık."},
{a: "HAMAK", m: "İki ağaç arasına gerilen sallanan yatak."},
{a: "KAPLAN", m: "Çizgili, büyük ve yırtıcı kedi türü."},
{a: "DÜRBÜN", m: "Uzağı yakın gösteren optik araç."},
{a: "AHTAPOT", m: "Sekiz kollu, denizlerde yaşayan vantuzlu canlı."},
{a: "İTFAİYE", m: "Yangın söndürme teşkilatı."},
{a: "CEVİZ", m: "Sert kabuklu, beyni andıran faydalı yemiş."},
{a: "PARAŞÜT", m: "Yüksekten güvenli inmeyi sağlayan kumaş araç."},
{a: "BERBER", m: "Saç ve sakal kesimi yapan kişi."},
{a: "KANGURU", m: "Kesesinde yavrusunu taşıyan zıplayan hayvan."},
{a: "ÇADIR", m: "Kamp yaparken barınılan taşınabilir barınak."},
{a: "GÖKKUŞAĞI", m: "Yağmurdan sonra oluşan yedi renkli yay."},
{a: "DİNAZOR", m: "Nesli tükenmiş dev sürüngen."},
{a: "AVİZE", m: "Tavandan sarkan süslü aydınlatma aracı."},
{a: "MİMAR", m: "Bina projelerini çizen kişi."},
{a: "KORSAN", m: "Denizlerde yağmacılık yapan kişi."},
{a: "ÇEKİRGE", m: "Zıplayarak hareket eden yeşil böcek."},
{a: "BALTA", m: "Odun kesmeye yarayan demir araç."},
{a: "EMZİK", m: "Bebeklerin susturulması için kullanılan plastik nesne."},
{a: "ORMAN", m: "Ağaçlarla kaplı geniş alan."},
{a: "DEDE", m: "Anne veya babanın babası."},
{a: "BESTECİ", m: "Müzik eseri yaratan sanatçı."},
{a: "MAKAS", m: "Kağıt veya kumaş kesmeye yarayan araç."},
{a: "HÖRGÜÇ", m: "Devenin sırtındaki çıkıntı."},
{a: "FÜZE", m: "Uzaya veya uzak mesafeye fırlatılan araç."},
{a: "KABAK", m: "Yemeği veya tatlısı yapılan iri sebze."},
{a: "BULAŞIK", m: "Yemekten sonra kirlenen mutfak eşyaları."},
{a: "KARINCA", m: "Çok çalışkan, küçük yer altı böceği."},
{a: "DÜDÜK", m: "Üfleyince keskin ses çıkaran araç."},
{a: "CAMİ", m: "Müslümanların ibadet ettiği yer."},
{a: "ELMAS", m: "Çok değerli ve en sert maden."},
{a: "KAYKAY", m: "Tekerlekli tahta üzerinde yapılan spor aracı."},
{a: "İSKELET", m: "Vücudun kemik çatısı."},
{a: "KAZAK", m: "Yünden örülen sıcak tutan giysi."},
{a: "ÇAKMAK", m: "Ateş yakmaya yarayan küçük araç."},
{a: "DEPREM", m: "Yer kabuğunun sarsılması olayı."},
{a: "KARPUZ", m: "Yazın yenen, içi kırmızı dışı yeşil büyük meyve."},
{a: "BEYGİR", m: "Atın bir diğer adı."},
{a: "KÜREK", m: "Toprak kazmaya veya sandal yürütmeye yarayan araç."},
{a: "GİTAR", m: "Telli ve parmakla çalınan bir çalgı."},
{a: "CÜCE", m: "Boyu normalden çok kısa olan kişi."},
{a: "OKYANUS", m: "Kıtaları birbirinden ayıran dev su kütlesi."},
{a: "ÇOBAN", m: "Hayvan sürülerini otlatan kişi."},
{a: "KEMAN", m: "Omuzda çalınan yaylı bir çalgı."},
{a: "ECZANE", m: "İlaç satılan yer."},
{a: "HAMSTER", m: "Evde beslenebilen küçük kemirgen."},
{a: "DOKTOR", m: "Hastaları tedavi eden eğitimli kişi."},
{a: "ÇERÇEVE", m: "Resim veya aynaların kenarına geçirilen kenarlık."},
{a: "BARAJ", m: "Su biriktirmek ve elektrik üretmek için yapılan yapı."},
{a: "KAVUN", m: "Sarı renkli, kokulu yaz meyvesi."},
{a: "HEYKEL", m: "Taş veya metalden yapılan sanat eseri."},
{a: "İSKELE", m: "Gemilerin yanaştığı platform."},
{a: "BALERİN", m: "Bale yapan kadın sanatçı."},
{a: "FESLEĞEN", m: "Güzel kokulu bir bitki türü."},
{a: "ÇÖL", m: "Kumlarla kaplı, suyun çok az olduğu geniş alan."},
{a: "BUĞDAY", m: "Un yapılan temel tarım bitkisi."},
{a: "KALE", m: "Savunma amaçlı yapılmış sağlam yapı."},
{a: "HARİTA", m: "Yeryüzünün kağıt üzerindeki çizimi."},
{a: "ÇEKİÇ", m: "Çivi çakmaya yarayan el aleti."},
{a: "ASTRONOT", m: "Uzay yolculuğu yapan eğitimli kişi."},
{a: "DOMATES", m: "Kırmızı, sulu ve çok tüketilen sebze."},
{a: "HOROZ", m: "Sabahları öten kümes hayvanı."},
{a: "MANTAR", m: "Toprakta yetişen, bazı türleri yenen bitki benzeri canlı."},
{a: "ÇİFTLİK", m: "Tarım ve hayvancılık yapılan arazi."},
{a: "KAPTAN", m: "Gemi veya uçağı yöneten kişi."},
{a: "DİNAMİT", m: "Patlayıcı madde."},
{a: "KUMBARA", m: "Para biriktirmek için kullanılan kutu."},
{a: "ÇELİK", m: "Demir ve karbon karışımı çok sert metal."},
{a: "FİLDİŞİ", m: "Filin uzun dişlerinden elde edilen değerli madde."},
{a: "AKVARYUM", m: "Balıkların içinde yaşadığı cam su kabı."},
{a: "HAVUÇ", m: "Turuncu renkli, tavşanların sevdiği sebze."},
{a: "DEĞİRMEN", m: "Tahıl öğüten veya enerji üreten yapı."},
{a: "ÇİNGENE", m: "Göçebe yaşam süren bir halk."},
{a: "FLÜT", m: "Üflemeli bir çalgı."},
{a: "CAMEKAN", m: "Dükkanların önündeki sergileme camı."},
{a: "ESKİMO", m: "Kutuplarda yaşayan yerli halk."},
{a: "ÇİZME", m: "Dize kadar çıkan koruyucu ayakkabı."},
{a: "ATLANTİK", m: "Dünyanın ikinci büyük okyanusu."},
{a: "GURUR", m: "Övünç duyma, onur."},
{a: "KOSTÜM", m: "Özel günlerde giyilen taklit kıyafeti."},
{a: "KAYIK", m: "Küçük deniz taşıtı."},
{a: "DÜNYA", m: "Üzerinde yaşadığımız gezegen."},
{a: "GAZETE", m: "Günlük haberleri veren basılı yayın."},
{a: "ARMADİLLO", m: "Vücudu sert bir kabukla kaplı olan memeli."},
{a: "CAN YELEĞİ", m: "Suda batmamayı sağlayan kıyafet."},
{a: "MERCEK", m: "Işığı kırarak görüntü büyüten cam."},
{a: "KÖMÜR", m: "Yeraltından çıkarılan siyah yanıcı maden."},
{a: "BASTON", m: "Yürürken destek alınan sopa."},
{a: "KUZU", m: "Koyunun yavrusu."},
{a: "HİPOPOTAM", m: "Su aygırı."},
{a: "KULE", m: "Çok yüksek ve ince yapı."},
{a: "GÜVERCİN", m: "Barışın simgesi olarak bilinen kuş."},
{a: "FINDIK", m: "Sert kabuklu küçük ve yuvarlak yemiş."},
{a: "BUZPATENİ", m: "Buz üzerinde kaymaya yarayan özel ayakkabı."},
{a: "BAYKUŞ", m: "Gece avlanan, başı çok dönebilen kuş."},
{a: "BEKÇİ", m: "Bir yeri korumakla görevli kişi."},
{a: "DEMİRYOLU", m: "Trenlerin üzerinde gittiği raylı yol."},
{a: "FİSKE", m: "Parmak ucuyla yapılan hafif vuruş."},
{a: "KAMYON", m: "Ağır yük taşıyan büyük araç."},
{a: "KAPLUMBAĞA", m: "Evini sırtında taşıyan yavaş hayvan."}, {a: "MIKNATIS", m: "Metalleri uzaktan çeken, buzdolabı kapaklarında da kullanılan nesne."},
{a: "PİPET", m: "Meyve suyu veya ayran kutularının yanındaki ince plastik boru."},
{a: "YELPAZE", m: "Eski zamanlarda kadınların serinlemek için ellerinde salladığı açılır kapanır eşya."},
{a: "ZIMBA", m: "Dağınık kağıtları birbirine bağlayan, içine metal tel konulan alet."},
{a: "PARAŞÜTÇÜ", m: "Uçaktan atlayıp gökyüzünde süzülerek yere inen sporcu."},
{a: "DALIŞ", m: "Tüp takarak veya nefes tutarak suyun derinliklerine inme eylemi."},
{a: "DENİZALTI", m: "Suyun en dibinden giderek görünmeden yol alan devasa gemi."},
{a: "KAKTÜS", m: "Çok az su isteyen, her yeri iğne gibi dikenlerle kaplı çöl bitkisi."},
{a: "GÖKDELEN", m: "Bulutlara kadar uzanıyormuş gibi görünen, çok yüksek şehir binası."},
{a: "LABİRENT", m: "İçinde birçok çıkmaz yol bulunan, çıkış kapısını bulmanın zor olduğu yer."},
{a: "KERPETEN", m: "İnşaatlarda veya tamiratta çivi sökmek için kullanılan metal el aleti."},
{a: "VANTİLATÖR", m: "Yazın odanın içinde dönerek rüzgar yapan pervaneli cihaz."},
{a: "PANDÜL", m: "Eski duvar saatlerinin altında sürekli sağa sola sallanan ağırlık."},
{a: "ASANSÖR", m: "Binalarda katlar arasında yorulmadan çıkmamızı sağlayan hareketli kabin."},
{a: "İTFAİYECİ", m: "Kırmızı arabasıyla gelip yangınları söndüren görevli kişi."},
{a: "TELGRAF", m: "Telefondan çok önce, dıt-dıt sesleriyle uzaktakilere mesaj gönderen cihaz."},
{a: "DÜRBÜN", m: "Maçlarda veya doğada uzağı daha net görmek için gözümüze tuttuğumuz alet."},
{a: "KAR KÜRESİ", m: "Sallayınca içindeki beyaz tanelerin havada uçuştuğu cam süs eşyası."},
{a: "POSTACI", m: "Kapıya gelip mektup veya fatura bırakan dağıtım görevlisi."},
{a: "YILDIRIM", m: "Fırtınalı havalarda gökyüzünden yere düşen çok güçlü ışık ve elektrik."},
{a: "ANTEN", m: "Televizyonun kanalları çekmesi için çatıya kurulan metal düzenek."},
{a: "VALİZ", m: "Tatile giderken bütün kıyafetlerimizi içine doldurduğumuz büyük çanta."},
{a: "KOVAN", m: "Binlerce arının bir arada yaşadığı ve petek yaptığı yuva."},
{a: "KASK", m: "Motorcuların kaza anında kafasını korumak için taktığı sert başlık."},
{a: "MATARA", m: "Yürüyüşte veya okulda yanımızda taşıdığımız su kabı."},
{a: "MÜHÜR", m: "Resmi kağıtların üzerine basılan, ıslak imza yerine de geçen damga."},
{a: "POTA", m: "Basketbol maçlarında topun içinden geçmesi gereken fileli çember."},
{a: "KORSAN", m: "Gözü bantlı, tahta bacaklı, denizlerde gemi soyan masal kahramanı."},
{a: "HEYBELİADA", m: "İstanbul'un faytonları ve çam ağaçlarıyla meşhur adalarından biri."},
{a: "SATRANÇ", m: "Şah ve mat yaparak rakibi yenmeye çalıştığınız taşlı oyun."},
{a: "HAMUR", m: "Ekmek veya börek yapmadan önce un ve suyla hazırlanan yumuşak kütle."},
{a: "FİRE", m: "Bir iş yapılırken malzemeden giden eksilme veya kayıp miktarı."},
{a: "SERA", m: "Kışın ortasında bile sebze yetişen, üstü naylon veya cam kaplı bahçe."},
{a: "KEPÇE", m: "Yemeği tencereden tabağa doldururken kullanılan büyük yuvarlak kaşık."},
{a: "GÖÇEBE", m: "Hayvancılıkla uğraşan ve çadırlarda yaşayıp sürekli yer değiştiren topluluk."},
{a: "PİRAMİT", m: "Mısır'da bulunan, firavunlar için yapılmış devasa üçgen taş mezar."},
{a: "TİYATRO", m: "Oyuncuların sahnede canlı performans sergilediği sanat dalı."},
{a: "REÇETE", m: "Eczaneden ilaç alabilmek için doktorun yazdığı imzalı kağıt."},
{a: "MÜEZZİN", m: "Günde beş vakit minareye çıkıp ezan okuyan kişi."},
{a: "HALTER", m: "Sporcuların iki ucu ağırlıklı demir çubuğu havaya kaldırdığı spor dalı."},
{a: "OLTA", m: "Deniz kenarında balık yakalamak için kullanılan iğneli ve ipli düzenek."},
{a: "MERCEK", m: "Büyüteçlerin içindeki, eşyaları daha büyük gösteren cam parça."},
{a: "KAVŞAK", m: "Şehir içinde birkaç farklı yolun birleştiği dönel nokta."},
{a: "SÖZLÜK", m: "Anlamını bilmediğimiz kelimelere bakmak için kullandığımız kitap."},
{a: "MÜREKKEP", m: "Kalemlerin yazmasını sağlayan renkli ve kalıcı sıvı."},
{a: "KELEBEK", m: "Rengarenk kanatları olan ve tırtıldan dönüşen narin böcek."},
{a: "UÇURTMA", m: "İple tutulan ve rüzgarda gökyüzünde süzülen kağıttan oyuncak."},
{a: "TERAZİ", m: "Manavda veya bakkalda meyvelerin kaç kilo geldiğini ölçen alet."},
{a: "KÜRE", m: "Futbol topu gibi her yeri tam yuvarlak olan şekil."},
{a: "PİKNİK", m: "Hafta sonu ormana gidip yerde yemek yeme ve eğlenme aktivitesi."},
{a: "KALECİ", m: "Futbol maçında ellerini kullanabilen ve kaleyi koruyan oyuncu."},
{a: "PARAŞÜT", m: "Uçaktan atlayınca havada açılan dev şemsiyeye benzeyen kumaş."},
{a: "SAZAN", m: "Göllerde yaşayan, pullu ve oltaya çabuk gelen bir balık."},
{a: "MEŞALE", m: "Eskiden kaleleri aydınlatmak için kullanılan ucu yanan sopa."},
{a: "VİDALI", m: "Tornavida ile döndürülerek takılan, dişli metal çivi."},
{a: "SAHNE", m: "Konserlerde şarkıcıların üzerine çıktığı yüksek platform."},
{a: "ZARF", m: "Mektubu gönderirken içine koyduğumuz kağıt kapak."},
{a: "KEVGİR", m: "Makarnanın suyunu süzmek için kullanılan delikli mutfak aracı."},
{a: "FÜZE", m: "Uzaya gitmek için kullanılan, arkasından ateş çıkan devasa araç."},
{a: "MADALYA", m: "Yarışmalarda dereceye girenlere boynuna takılan metal ödül."},
{a: "KAYIKÇI", m: "Küçük teknelerle insanları suyun karşı tarafına geçiren kişi."},
{a: "GÖLGE", m: "Güneşli havada vücudumuzun yerde oluşan siyah görüntüsü."},
{a: "TEBESSÜM", m: "Kahkaha atmadan, sadece dudaklarla yapılan hafif gülümseme."},
{a: "KÜS", m: "Arkadaşıyla kavga edip onunla konuşmayan kişinin durumu."},
{a: "VALİ", m: "Bir şehri yöneten en yetkili devlet görevlisi."},
{a: "MÜFETTİŞ", m: "Okulları veya iş yerlerini denetlemeye gelen yetkili uzman."},
{a: "NÖBETÇİ", m: "Gece her yer kapalıyken açık kalan eczane veya bekleyen asker."},
{a: "SİHİRBAZ", m: "Şapkadan tavşan çıkaran, illüzyon numaraları yapan kişi."},
{a: "MÜCEVHER", m: "Altın, pırlanta gibi çok değerli taşlarla yapılan takı."},
{a: "YELKEN", m: "Rüzgarın gücüyle gemiyi denizde yürüten büyük kumaş."},
{a: "SÖYLEŞİ", m: "Bir topluluğun önünde yapılan keyifli ve bilgilendirici sohbet."},
{a: "KRONOMETRE", m: "Koşu yarışlarında süreyi ölçmek için kullanılan hassas saat."},
{a: "FOTOĞRAFÇI", m: "Özel günlerde gelip makinesiyle resimlerimizi çeken sanatçı."},
{a: "MÜHENDİS", m: "Bina, yol, makine veya yazılım tasarlayan teknik uzman."},
{a: "TABELA", m: "Dükkanların üstünde ne sattığını yazan bilgilendirme levhası."},
{a: "KRAMPON", m: "Futbolcuların çim sahada kaymaması için altı çivili ayakkabısı."},
{a: "ANTRENMAN", m: "Maça çıkmadan önce yapılan hazırlık çalışması."},
{a: "KUPA", m: "Şampiyon olan takıma verilen büyük ve gösterişli ödül."},
{a: "VİRÜS", m: "İnsanları hasta eden, gözle görülmeyen çok küçük mikrop."},
{a: "AŞI", m: "Hastalık kapmamak için koldan yapılan koruyucu iğne."},
{a: "HEMŞİRE", m: "Hastanede iğne yapan ve doktorlara yardım eden görevli."},
{a: "STADYUM", m: "Binlerce insanın maç izlemek için toplandığı dev spor alanı."},
{a: "SİNCAP", m: "Ceviz ve fındık yiyen, ağaçlarda gezen kuyruklu hayvan."},
{a: "BUKALEMUN", m: "Girdiği yerin rengini alabilen, dili çok uzun sürüngen."},
{a: "KANGURU", m: "Karnındaki kesesinde yavrusunu taşıyan ve zıplayan hayvan."},
{a: "PENGUEN", m: "Kutuplarda yaşayan, paytak yürüyen ve uçamayan kuş."},
{a: "KUTUP", m: "Dünyanın en alt ve en üstünde bulunan buzlarla kaplı yerler."},
{a: "DİNAZOR", m: "Çok eski zamanlarda yaşamış, nesli tükenmiş dev yaratık."},
{a: "FOSİL", m: "Milyonlarca yıl önceden kalan taşlaşmış kemik veya iz."},
{a: "KRATER", m: "Yanardağların tepesinde bulunan derin çukur."},
{a: "GÖKTAŞI", m: "Uzaydan gelip dünyaya düşen dev kaya parçası."},
{a: "GEZEGEN", m: "Dünya, Mars veya Jüpiter gibi gökyüzünde dönen büyük cisimler."},
{a: "ASTRONOT", m: "Özel kıyafetini giyip uzay gemisiyle keşfe çıkan kişi."},
{a: "TELESKOP", m: "Yıldızları ve diğer gezegenleri incelemeye yarayan dev alet."},
{a: "SİSMOGRAF", m: "Depremin ne kadar güçlü olduğunu ölçen cihaz."},
{a: "HİDROJEN", m: "En hafif olan ve evrende en çok bulunan gaz."},
{a: "OKSİJEN", m: "Nefes almamız için havada bulunan en önemli gaz."},
{a: "KARBONDİOKSİT", m: "Nefes verirken dışarı attığımız, ağaçların sevdiği gaz."},
{a: "AZOT", m: "Soluduğumuz havanın çoğunluğunu oluşturan renksiz gaz."},
{a: "OZON", m: "Güneşin zararlı ışınlarını engelleyen koruyucu gökyüzü tabakası."},
    {a: "ÜTÜ", m: "Kırışıklıkları gidermek için kullanılan ısıtmalı araç."},
    {a: "FİRE", m: "İşlem sırasında oluşan ağırlık veya miktar kaybı."},
    {a: "SİLİ", m: "Temizlikte kullanılan ıslak veya kuru bez."},
    {a: "KOTA", m: "Sınırlama veya belirlenen miktar sınırı."},
    {a: "İKON", m: "Simge haline gelmiş kişi veya işaret."},
    {a: "SÖTE", m: "Hafif ateşte az yağ ile pişirme yöntemi."},
    {a: "FİŞEK", m: "Silahların içine konulan patlayıcı madde."},
    {a: "BAGAJ", m: "Taşıtların arkasındaki eşya koyma bölümü."},
    {a: "METRE", m: "Uzunluk ölçmek için kullanılan temel birim."},
    {a: "SALON", m: "Evin en büyük ve misafir ağırlanan odası."},
    {a: "TÜTSÜ", m: "Yakıldığında güzel koku yayan madde."},
    {a: "BÖLGE", m: "Sınırları belirlenmiş toprak parçası."},
    {a: "FLAMA", m: "İşaret olarak kullanılan küçük üçgen bayrak."},
    {a: "KORER", m: "Savunma oyuncularının topu dışarı atması durumu."},
    {a: "RADAR", m: "Hız tespiti yapan elektronik cihaz."},
    {a: "PİJAMA", m: "Yatarken giyilen rahat kıyafet."},
    {a: "KABARE", m: "Güncel konuların eleştiriyle anlatıldığı tiyatro."},
    {a: "İSKELE", m: "Deniz kıyısına yapılan gemi yanaşma yeri."},
    {a: "MİKROP", m: "Hastalık yapan gözle görülmeyen canlı."},
    {a: "TÖRPÜ", m: "Yüzeyleri pürüzsüzleştiren tırtıklı alet."},
    {a: "PANTER", m: "Hızlı ve çevik siyah yırtıcı kedi."},
    {a: "MANTAR", m: "Toprakta yetişen sporla üreyen canlı."},
    {a: "HORTUM", m: "Su taşımaya yarayan plastik boru."},
    {a: "HEYKEL", m: "Taş veya metalden yapılan sanat eseri."},
    {a: "PİRİNÇ", m: "Pilav yapımında kullanılan tahıl."},
    {a: "DANTEL", m: "İnce iplerle örülen süslü el işi."},
    {a: "BOMBA", m: "Patlayıcı içeren düzenek."},
    {a: "KÖPRÜ", m: "İki yakayı birbirine bağlayan yapı."},
    {a: "SARMAL", m: "Helezon şeklinde kıvrılmış olan."},
    {a: "KİMLİK", m: "Kişinin kim olduğunu belirten belge."},
    {a: "ZİNCİR", m: "Halkaların birbirine geçmesiyle oluşan bağ."},
    {a: "ŞÖVALYE", m: "Eski zamanların zırhlı ve atlı savaşçısı."},
    {a: "PARSEL", m: "İmar yasasına göre bölünmüş toprak parçası."},
    {a: "GÖZLÜK", m: "Görme kusurlarını gideren optik araç."},
    {a: "REKLAM", m: "Ürün tanıtımı için yapılan faaliyet."},
    {a: "KERESTE", m: "İnşaat işlerinde kullanılan kesilmiş ağaç."},
    {a: "PIRANHA", m: "Amazon nehrinde yaşayan yırtıcı balık."},
    {a: "FIRTINA", m: "Çok şiddetli esen rüzgar ve yağış."},
    {a: "SİGORTA", m: "Elektrik devresini veya eşyayı güvenceye alan sistem."},
    {a: "KOLONYA", m: "Alkol bazlı ferahlatıcı güzel kokulu sıvı."},
    {a: "PİRAMİT", m: "Üçgen yüzeyli anıtsal yapı."},
    {a: "STADYUM", m: "Spor müsabakalarının yapıldığı dev tesis."},
    {a: "LOKANTA", m: "Yemek yenilen ticari işletme."},
    {a: "DİKKATİ", m: "Zihnin bir konu üzerinde yoğunlaşması."},
    {a: "SİHİRBAZ", m: "İllüzyon gösterisi yapan sanatçı."},
    {a: "YAYINEVİ", m: "Kitap basan ve dağıtan kuruluş."},
    {a: "İSKOÇYA", m: "Birleşik Krallık'ta bulunan bir ülke."},
    {a: "TRAKTÖR", m: "Tarlada iş yapmaya yarayan güçlü araç."},
    {a: "SERAMİK", m: "Pişmiş topraktan yapılan eşya."},
    {a: "TEBESSÜM", m: "Dudak ucuyla yapılan hafif gülüş."},
    {a: "DENEYİM", m: "Bir işi yaparak kazanılan tecrübe."},
    {a: "OKYANUS", m: "Kıtalar arası devasa su kütlesi."},
    {a: "MÜHİMMAT", m: "Savaş için gerekli patlayıcı ve mermiler."},
    {a: "PARFÜM", m: "Vücuda sıkılan güzel koku."},
    {a: "KORİDOR", m: "Binalarda odalar arası geçit."},
    {a: "DETERJAN", m: "Temizlikte kullanılan kimyasal madde."},
    {a: "KAFETERYA", m: "Hafif yemek ve içecek satılan yer."},
    {a: "MÜCEVHER", m: "Altın ve değerli taşlardan yapılan takı."},
    {a: "KRONOMETRE", m: "Zamanı saniyenin altına kadar ölçen araç."},
    {a: "TELESKOP", m: "Gök cisimlerini inceleyen optik cihaz."},
    {a: "PSİKOLOG", m: "Ruh sağlığı ve davranış uzmanı."},
    {a: "KARABİBER", m: "Yemeklere tat veren siyah taneli baharat."},
    {a: "GÜNEŞLİK", m: "Güneş ışığını kesmek için kullanılan örtü."},
    {a: "OPERATÖR", m: "Bir makineyi veya sistemi yöneten kişi."},
    {a: "TEKNOLOJİ", m: "Bilimsel bilgilerin pratik kullanımı."},
    {a: "FOTOĞRAF", m: "Işıkla dondurulmuş an görüntüsü."},
    {a: "REHBERLİK", m: "Yol gösterme ve danışmanlık hizmeti."},
    {a: "DOMATESLİ", m: "İçinde domates bulunan karışım."},
    {a: "JENERATÖR", m: "Mekanik enerjiyi elektriğe çeviren cihaz."},
    {a: "ZİYARETÇİ", m: "Bir yere görmeye veya bakmaya gelen kişi."},
    {a: "BUZDOLABI", m: "Yiyecekleri soğuk tutan mutfak cihazı."},
    {a: "YÖNETMELİK", m: "Bir işin nasıl yapılacağını gösteren kurallar."},
    {a: "DİSTRİBÜTÖR", m: "Bir markanın ürünlerini dağıtan ana bayi."},
    {a: "ANTRENMAN", m: "Hazırlık amacıyla yapılan düzenli çalışma."},
    {a: "BİSİKLETÇİ", m: "Bisiklet süren veya tamir eden kişi."},
    {a: "PİYANİST", m: "Piyano çalma sanatını icra eden kişi."},
    {a: "KOORDİNAT", m: "Bir noktanın konumunu belirten sayılar."},
    {a: "ANSİKLOPEDİ", m: "Bilgilerin alfabetik verildiği dev kitap dizisi."},
    {a: "MÜHENDİSLİK", m: "Teknik projeler geliştirme mesleği."},
    {a: "KİREÇLEME", m: "Yüzeyi kireçle kaplama işlemi."},
    {a: "BİLGİSAYAR", m: "Veri işleme ve saklama yeteneği olan cihaz."},
    {a: "HİDROELEKTRİK", m: "Su gücüyle elde edilen enerji türü."},
    {a: "PROJEKSİYON", m: "Görüntüyü perdeye yansıtan cihaz."},
    {a: "VANTİLATÖR", m: "Dönerek rüzgar yapan soğutma aracı."},
    {a: "KOLEKSİYON", m: "Özenle biriktirilmiş eşyalar bütünü."},
    {a: "KİBİRLEŞMEK", m: "Kendini başkalarından üstün görme durumu."},
    {a: "GÖKKUŞAĞI", m: "Yağmur sonrası çıkan renkli yay."},
    {a: "KARBONDİOKSİT", m: "Nefes verirken dışarı atılan gaz."},
    {a: "KUMARBAZLAR", m: "Şans oyunlarını alışkanlık edinenler."},
    {a: "ASTRONOMİK", m: "Gök bilimi ile ilgili veya çok büyük rakam."},
    {a: "KARTONPİYER", m: "Tavan süslemesinde kullanılan alçı malzeme."},
    {a: "REHABİLİTASYON", m: "Yeniden sağlık kazandırma süreci."},
    {a: "KÜRESELLEŞME", m: "Dünyanın tek bir pazar haline gelmesi."},
    {a: "MİLLİYETÇİLİK", m: "Ulusunu ve vatanını sevme ülküsü."},
    {a: "TRAFİK LAMBASI", m: "Ulaşımı düzenleyen ışıklı sistem."},
    {a: "DENİZALTI", m: "Suyun altından giden askeri gemi."},
    {a: "İTFAİYECİ", m: "Yangınla mücadele eden kahraman görevli."},
    {a: "PARSÖNELLEŞME", m: "Kişiye özel hale getirme durumu."},
    {a: "ÖRGÜTLENMEK", m: "Bir amaç için bir araya gelip düzen kurmak."},
    {a: "MİKROFONLU", m: "Ses kayıt sistemi olan düzenek."}
];


];
