export const wordList = [
            {a: "AĞAÇ", m: "gövdesi odun olan bitki."}, {a: "ALTIN", m: "değerli sarı maden."}, {a: "ANNE", m: "Cennetin ayaklarının altında olduğu müjdelenen kişi."}, {a: "ARABA", m: "4 tekerlekli genellikle üstü kapalı olan taşıt."}, {a: "BALIK", m: "Nefes almak için suya muhtaç olan canlı."}, {a: "BEBEK", m: "Ailenin Yeni üyesi"}, {a: "BEYİN", m: "sinir sisteminin merkezi."}, {a: "BİLGİ", m: "Öğrenilen her şeyin toplamı, başarının anahtarı."}, {a: "BULUT", m: "Gökyüzünde görülen su damlacıklarından oluşan küme."}, {a: "ÇANTA", m: "İçine eşya konur elde ya da omuzda taşınır."}, {a: "ÇİÇEK", m: "Bitkilerin üreme organı olan kısım."}, {a: "ÇOCUK", m: "henüz büyüyememiş birey"}, {a: "DENİZ", m: "geniş tuzlu su kütlesi."}, {a: "DEFTER", m: "Bilgilerin düzenli şekilde tutulduğu kağıtlar bütünü."}, {a: "DOST", m: "Bağ kurulan samimi insan"}, {a: "DUVAR", m: "Mekanları sınırlandıran sabit yapı öğesi."}, {a: "ELMA", m: "Kırmızı yeşil ya da sarı olabilen tatlı bir meyve."}, {a: "EV", m: "Günlük hayatın geçtiği yaşam alanı."}, {a: "FENER", m: "pil ile çalışan aydınlatma aracı."}, {a: "GEMİ", m: "Uzun yolculuklar yapan büyük su taşıtı"}, {a: "GÖZ", m: "görme organı."}, {a: "GÜNEŞ", m: "dünyayı aydınlatan yıldız."}, {a: "HAVA", m: "Canlı yaşamı için gerekli gaz ."}, {a: "HAYAT", m: "Doğumdan ölüme kadar geçen zaman."}, {a: "IRMAK", m: "Denize dökülen büyük akarsu."}, {a: "IŞIK", m: "görmeyi sağlayan enerji."}, {a: "KALEM", m: "Düşünceleri yazıya dökmeye yarayan araç."}, {a: "KAPI", m: "Giriş çıkışı sağlayan açılıp kapanan bölüm."}, {a: "KEDİ", m: "memeli hayvanlar sınıfına ait, küçük boyutlu, çevik ve etçil bir türdür."}, {a: "KİTAP", m: "Bilgi veya hikâye içeren basılı eser."}, {a: "KÖPRÜ", m: "iki yeri bağlayan yapı."}, {a: "KUŞ", m: "uçabilen hayvan."}, {a: "MASA", m: "üzerinde ders çalıştığımız mobilya."}, {a: "OKUL", m: "eğitim verilen yer."}, {a: "OYUN", m: "Yetenek ve zekâ geliştirici, belli kuralları olan, iyi vakit geçirmeye yarayan eğlence."}, {a: "PENCERE", m: "Işık ve hava girişi sağlayan açıklık."},{a: "SU", m: "yaşam için gerekli sıvı."}, {a: "TOP", m: "yuvarlak oyun aracı."}, {a: "UYKU", m: "dinlenme hali."}, {a: "YAZI", m: "harflerle anlatım."}, {a: "YILDIZ", m: "Gökyüzünde kendi ışığını yayarak parlayan gök cismi."}, {a: "YOL", m: "Ulaşım ve geçiş için kullanılan alan."}, {a: "KUM", m: "Deniz ve çöllerde bulunan çok küçük taş taneleri."},{a: "MUTFAK", m: "yemek yapılan yer."}, {a: "BİBER", m: "acı veya tatlı sebze."}, {a: "SAKIZ", m: "Çiğnenen ve ağızda dağılan esnek madde."}, {a: "ÇATI", m: "Bir yapının üstünü örten ve koruyan bölüm."}, {a: "YASTIK", m: "Uyurken başın altına konulan yumuşak eşya."}, {a: "KİRPİ", m: "dikenli küçük hayvan."}, {a: "OYUNCAK", m: "Çocukların oynaması için yapılan eşya."}, {a: "ÇAY", m: "Demlenerek hazırlanan sıcak içecek."}, {a: "GÖL", m: "Karalarla çevrili durgun su birikintisi."}, {a: "KART", m: "Alışveriş ve ödeme yapmaya yarayan plastik kart."}, {a: "MÜZİK", m: "İnsanları etkileyen ve zevk veren ses düzeni."}, {a: "SİNEK", m: "Havada dolaşan ve vızıldayan küçük haşere."}, {a: "BALON", m: "İçi hava veya gazla doldurulan hafif oyuncak."}, {a: "BÜYÜKADA", m: "istanbulda bir ada."}, {a: "MAYMUN", m: "İnsana benzeyen hareketleri olan kuyruklu memeli."}, {a: "HAVA", m: "yaşam için gerekli gaz."}, {a: "KÖPEK", m: "Evleri koruyan ve eğitilebilen hayvan."}, {a: "ÇORAP", m: "Ayağı sıcak tutmak için giyilen giysi."}, {a: "BİLGİSAYAR", m: "Bilgi işleyen ve saklayan elektronik cihaz."}, {a: "FOTOĞRAF", m: "resim veya görüntü kaydı."}, {a: "MOTOR", m: "Hareket üretmek için enerjiyi mekanik güce çeviren makine."}, {a: "ŞEMSİYE", m: "Yağmur ve güneşten korunmak için kullanılan açılır kapanır araç."}, {a: "LAMBA", m: "ışık veren aydınlatma aracı."}, {a: "BİYOLOJİ", m: "canlıları inceleyen bilim."}, {a: "TAVŞAN", m: "Hızlı koşan ve uzun kulaklı memeli hayvan."}, {a: "ŞEHİR", m: "İnsanların yoğun olarak yaşadığı yerleşim alanı."}, {a: "KUYRUK", m: "Bazı hayvanların arka kısmında bulunan uzantı."}, {a: "YUMURTA", m: "tavuk ve kuşların ürünü."}, {a: "BİBERON", m: "Emzik ve ağızdan beslenmeyi sağlayan kaplı araç."}, {a: "ÇÖP", m: "atık madde."}, {a: "MUTLULUK", m: "iyi hissetme durumu."}, {a: "GÖZLÜK", m: "görmeyi kolaylaştıran araç."}, {a: "ÇİZİM", m: "Kalem veya fırça ile yapılan resim veya tasarım."}, {a: "AYAKKABI", m: "ayak koruyucu giysi."}, {a: "TÜRKİYE", m: "81 ili olan ülke."}, {a: "BİRLİK", m: "bir araya gelme durumu."}, {a: "ÇORBA", m: "Sulu ve yiyeceklerle yapılan sıcak yemek."}, {a: "KUMANDA", m: "cihazı uzaktan kontrol eden eşya."}, {a: "KÖY", m: "küçük yerleşim yeri."}, {a: "KUAFÖR", m: "saç kesimi ve bakım hizmeti veren yer."}, {a: "PİZZA", m: "Üzerine peynir, sos ve malzeme konularak fırında pişirilen yiyecek."}, {a: "ŞEKER", m: "Tatlı ve genellikle küçük katı yiyecek."}, {a: "BAYRAK", m: "ülke simgesi."}, {a: "MÜZE", m: "eserlerin sergilendiği yer."}, {a: "TÜNEL", m: "yer altından geçen yol."}, {a: "KİLİT", m: "Kapıları veya eşyaları güvenli hale getiren araç."}, {a: "BANDANA", m: "Baş veya boyuna bağlanan ince kumaş parça."}, {a: "KAFES", m: "Hayvanları içinde tutmak için yapılan tel veya demirden yapı."}, {a: "YAY", m: "Esnek malzeme ile energy depolayan ve fırlatma aracı."}, {a: "ÇİMENTO", m: "Binalarda sağlamlık sağlamak için kullanılan toz malzeme"}, {a: "TRAFO", m: "Elektrik voltajını yükselten veya düşüren cihaz."}, {a: "FIRIN", m: "Isı ve ısıtma ile yiyecekleri pişiren mutfak aracı."}, {a: "RADYO", m: "ses ile bilgi veren cihaz."}, {a: "KABLO", m: "elektrik veya veri taşıyan tel."}, {a: "TELEFON", m: "Sesli ve yazılı iletişim kurmayı sağlayan cihaz."}, {a: "KASABA", m: "şehirden küçük yerleşim yeri."}, {a: "KAHVE", m: "Kavrulmuş çekirdeklerden hazırlanan sıcak içecek."}, {a: "BASKETBOL", m: "İki takımın topu potaya atarak sayı yaptığı spor oyunu."}, {a: "PASTANE", m: "tatlı ve yiyecek yapılan yer."}, {a: "TAVUK", m: "kümes hayvanı."}, {a: "KARTON", m: "kalın kağıt türü."}, {a: "GÜL", m: "çiçek türü."}, {a: "ADALET", m: "hak ve doğruluğa uygunluk."}, {a: "AKIL", m: "düşünme ve anlama yeteneği."}, {a: "ALARM", m: "uyarı veren sistem."}, {a: "AYNA", m: "yansıma sağlayan cam."}, {a: "BAHÇE", m: "bitki yetiştirilen alan."}, {a: "BANT", m: "yapıştırıcı şerit."}, {a: "BARDAK", m: "sıvı içmeye yarayan kap."}, {a: "BATTANİYE", m: "örtünmek için kullanılan kalın örtü."}, {a: "BİSİKLET", m: "pedallı iki tekerlekli araç."}, {a: "BORU", m: "sıvı veya gaz taşıyan kanal."}, {a: "BUZDOLABI", m: "yiyecekleri soğutan cihaz."}, {a: "CEKET", m: "üst vücuda giyilen giysi."}, {a: "CÜZDAN", m: "para ve kart konulan eşya."}, {a: "DERS", m: "öğrenme amacıyla yapılan etkinlik."}, {a: "DOLAP", m: "eşya saklanan mobilya."}, {a: "DÜĞME", m: "giysileri iliklemeye yarayan parça."}, {a: "EKRAN", m: "görüntü gösteren yüzey."}, {a: "ELDİVEN", m: "eli koruyan giysi."}, {a: "FATURA", m: "ödeme belgesi."}, {a: "FIRÇA", m: "temizlik veya boyama aracı."}, {a: "GARDIROP", m: "giysi dolabı."}, {a: "GÖMLEK", m: "üst vücuda giyilen kıyafet."}, {a: "HALI", m: "zemine serilen eşya."}, {a: "HOPARLÖR", m: "ses çıkaran cihaz."}, {a: "İLAÇ", m: "hastalık tedavisinde kullanılan madde."}, {a: "İPEK", m: "böcekten elde edilen ince lif."}, {a: "KAĞIT", m: "yazı yazmaya yarayan yüzey."}, {a: "KASK", m: "baş koruyucu ekipman."}, {a: "KETÇAP", m: "domatesten yapılan sos."}, {a: "KLAVYE", m: "yazı girişi yapılan tuş takımı."}, {a: "KOLTUK", m: "oturmak için kullanılan eşya."}, {a: "KREM", m: "cilt bakım ürünü."}, {a: "LİMON", m: "ekşi bir meyve."}, {a: "LOKMA", m: "küçük yiyecek parçası."}, {a: "MANDAL", m: "çamaşır tutturma aracı."}, {a: "MERDİVEN", m: "katlar arası geçiş yapısı."}, {a: "MİKROFON", m: "ses kaydetme aracı."}, {a: "MONİTÖR", m: "bilgisayar görüntü birimi."}, {a: "NALBUR", m: "yapı malzemesi satan yer."}, {a: "NOT", m: "kısa yazılı hatırlatma."}, {a: "OBJEKTİF", m: "fotoğraf makinesi parçası."}, {a: "ORGAN", m: "canlı vücudu parçası."}, {a: "OTOBÜS", m: "toplu taşıma aracı."}, {a: "PANO", m: "bilgi asılan yüzey."}, {a: "PANTOLON", m: "alt vücuda giyilen giysi."}, {a: "PİL", m: "taşınabilir enerji kaynağı."}, {a: "PRİZ", m: "elektrik bağlantı noktası."}, {a: "RAF", m: "eşya koyma bölmesi."}, {a: "SANDALYE", m: "oturmak için kullanılan eşya."}, {a: "SÜPÜRGE", m: "temizlik aracı."}, {a: "TABAK", m: "Yemek koymaya yarayan mutfak eşyası"}, {a: "TAKVİM", m: "günleri gösteren çizelge."}, {a: "TERLİK", m: "ev içinde giyilen ayakkabı."}, {a: "TİŞÖRT", m: "kısa kollu üst giysi."}, {a: "TORBA", m: "eşya taşıma aracı."}, {a: "TRAFİK", m: "araç ve yaya yoğunluğu."}, {a: "UÇAK", m: "havada yolculuk aracı."}, {a: "ÜTÜ", m: "Kıyafetlerdeki kırışıklıkları gidermeye yarayan alet."}, {a: "VİTRİN", m: "ürün sergilenen camlı alan."}, {a: "YEMEK", m: "beslenme amacıyla tüketilen şey."}, {a: "YOĞURT", m: "Sütün mayalanmasıyla elde edilen koyu kıvamlı ekşi tatlı bir süt ürünüdür"}, {a: "ZARF", m: "mektup konulan kağıt."},{a: "AKREP", m: "Zehrli sokma özelliği olan küçük hayvan."},
{a: "ARMUT", m: "Tatlı ve sulu meyve."},
{a: "AT", m: "İnsan veya yük taşımada kullanılan hızlı hayvan."},
{a: "AYI", m: "Büyük ve güçlü memeli hayvan."},
{a: "BÖCEK", m: "Küçük ve çok bacaklı omurgasız canlı."},
{a: "ÇİTA", m: "Dünyanın en hızlı kara hayvanı."},
{a: "DENİZYILDIZI", m: "Denizlerde yaşayan beş kollu canlı."},
{a: "FOK", m: "Suda yaşayan memeli hayvan."},
{a: "GEYİK", m: "Boynuzlu orman hayvanı."},
{a: "HIRSIZ", m: "Başkasının malını çalan kişi."},
{a: "İNEK", m: "Süt veren çiftlik hayvanı."},
{a: "JEL", m: "Yarı sıvı kıvamında madde."},
{a: "KAKTÜS", m: "Sulu ve dikenli bitki."},
{a: "LAPA", m: "Yoğun kar veya çamur birikintisi."},
{a: "MANGO", m: "Tropikal ve tatlı meyve."},
{a: "NEKTAR", m: "Çiçeklerden toplanan tatlı sıvı."},
{a: "OBJE", m: "Belirli amaçla kullanılan nesne."},
{a: "PANDA", m: "Siyah beyaz ve bambu yiyen hayvan."},
{a: "RAPOR", m: "Olay veya durum hakkında yazılı bilgi."},
{a: "SAL", m: "Küçük ve açık su aracı."},
{a: "TAVSİYE", m: "Bir konuda yol gösteren öneri."},
{a: "UĞURBÖCEĞİ", m: "Küçük ve kırmızı benekli böcek."},
{a: "VİYOLA", m: "Keman ailesinden yaylı çalgı."},
{a: "YELKENCİ", m: "Yelkenli tekne ile seyahat eden kişi."},
{a: "ZEBRA", m: "Çizgili ve otçul hayvan."},
{a: "AMBAR", m: "Eşya veya mal depolanan büyük yer."},
{a: "BİLGİSAYARCI", m: "Bilgisayar ile çalışan kişi."},
{a: "CİVCİV", m: "Yeni doğmuş tavuk."},
{a: "DİKİŞ", m: "İplik ile yapılan birleştirme işlemi."},
{a: "ELBİSE", m: "Vücut için giyilen giysi."},
{a: "FOSFOR", m: "Işığı yansıtan kimyasal element."},
{a: "GÖLGE", m: "Işığın engellenmesi ile oluşan karanlık alan."},
{a: "HIRS", m: "Fazla arzu veya tamah."},
{a: "ISITICI", m: "Alanı veya nesneyi ısıtan cihaz."},
{a: "JAPON", m: "Japonya vatandaşına denir."},
{a: "KİLOMETRE", m: "Uzunluk ölçü birimi."},
{a: "LİSANSLI", m: "Resmî izin veya belgeye sahip."},
{a: "MÜREKKEP", m: "Yazı yazmak için kullanılan sıvı boya."},
{a: "NELER", m: "Soru zamiri."},
{a: "ORTAOKUL", m: "İlkokuldan sonra öğrenim verilen kurum."},
{a: "PİYANO", m: "Tuşlu ve yaylı çalgı."},
{a: "RAFİNERİ", m: "Ham petrol işlenen fabrika."},
{a: "SOKAK", m: "Binalar arasında geçen yol."},
{a: "TOPLANTI", m: "Bir amaç için insanların bir araya gelmesi."},
{a: "ULUS", m: "Ortak kültür ve dili olan insanlar topluluğu."},
{a: "VİRAJ", m: "Yolun dönemeçli kısmı."},
{a: "YEL", m: "Hareket eden hava."},
{a: "ZİNCİR", m: "Halka halkaya bağlı metal parça."},
{a: "AÇIKHAVA", m: "Kapalı olmayan dış mekan."},
{a: "BİTKİ", m: "Toprakta büyüyen canlı organizma."},
{a: "ÇİZİK", m: "Yüzeyde oluşan ince çizgi veya hasar."}, {a: "EJDERHA", m: "Masallarda ağzından ateş çıkaran dev yaratık."},
{a: "HAMAK", m: "İki ağaç arasına gerilen sallanan yatak."},
{a: "KAPLAN", m: "Çizgili, büyük ve yırtıcı kedi türü."},
{a: "DÜRBÜN", m: "Uzağı yakın gösteren optik araç."},
{a: "AHTAPOT", m: "Sekiz kollu, denizlerde yaşayan vantuzlu canlı."},
{a: "İTFAİYE", m: "Yangın söndürme teşkilatı."},
{a: "CEVİZ", m: "Sert kabuklu, beyni andıran faydalı yemiş."},
{a: "PARAŞÜT", m: "Yüksekten güvenli inmeyi sağlayan kumaş araç."},
{a: "BERBER", m: "Saç ve sakal kesimi yapan kişi."},
{a: "KANGURU", m: "Kesesinde yavrusunu taşıyan zıplayan hayvan."},
{a: "ÇADIR", m: "Kamp yaparken barınılan taşınabilir barınak."},
{a: "GÖKKUŞAĞI", m: "Yağmurdan sonra oluşan yedi renkli yay."},
{a: "DİNAZOR", m: "Nesli tükenmiş dev sürüngen."},
{a: "AVİZE", m: "Tavandan sarkan süslü aydınlatma aracı."},
{a: "MİMAR", m: "Bina projelerini çizen kişi."},
{a: "KORSAN", m: "Denizlerde yağmacılık yapan kişi."},
{a: "ÇEKİRGE", m: "Zıplayarak hareket eden yeşil böcek."},
{a: "BALTA", m: "Odun kesmeye yarayan demir araç."},
{a: "EMZİK", m: "Bebeklerin susturulması için kullanılan plastik nesne."},
{a: "ORMAN", m: "Ağaçlarla kaplı geniş alan."},
{a: "DEDE", m: "Anne veya babanın babası."},
{a: "BESTECİ", m: "Müzik eseri yaratan sanatçı."},
{a: "MAKAS", m: "Kağıt veya kumaş kesmeye yarayan araç."},
{a: "HÖRGÜÇ", m: "Devenin sırtındaki çıkıntı."},
{a: "FÜZE", m: "Uzaya veya uzak mesafeye fırlatılan araç."},
{a: "KABAK", m: "Yemeği veya tatlısı yapılan iri sebze."},
{a: "BULAŞIK", m: "Yemekten sonra kirlenen mutfak eşyaları."},
{a: "KARINCA", m: "Çok çalışkan, küçük yer altı böceği."},
{a: "DÜDÜK", m: "Üfleyince keskin ses çıkaran araç."},
{a: "CAMİ", m: "Müslümanların ibadet ettiği yer."},
{a: "ELMAS", m: "Çok değerli ve en sert maden."},
{a: "KAYKAY", m: "Tekerlekli tahta üzerinde yapılan spor aracı."},
{a: "İSKELET", m: "Vücudun kemik çatısı."},
{a: "KAZAK", m: "Yünden örülen sıcak tutan giysi."},
{a: "ÇAKMAK", m: "Ateş yakmaya yarayan küçük araç."},
{a: "DEPREM", m: "Yer kabuğunun sarsılması olayı."},
{a: "KARPUZ", m: "Yazın yenen, içi kırmızı dışı yeşil büyük meyve."},
{a: "BEYGİR", m: "Atın bir diğer adı."},
{a: "KÜREK", m: "Toprak kazmaya veya sandal yürütmeye yarayan araç."},
{a: "GİTAR", m: "Telli ve parmakla çalınan bir çalgı."},
{a: "CÜCE", m: "Boyu normalden çok kısa olan kişi."},
{a: "OKYANUS", m: "Kıtaları birbirinden ayıran dev su kütlesi."},
{a: "ÇOBAN", m: "Hayvan sürülerini otlatan kişi."},
{a: "KEMAN", m: "Omuzda çalınan yaylı bir çalgı."},
{a: "ECZANE", m: "İlaç satılan yer."},
{a: "HAMSTER", m: "Evde beslenebilen küçük kemirgen."},
{a: "DOKTOR", m: "Hastaları tedavi eden eğitimli kişi."},
{a: "ÇERÇEVE", m: "Resim veya aynaların kenarına geçirilen kenarlık."},
{a: "BARAJ", m: "Su biriktirmek ve elektrik üretmek için yapılan yapı."},
{a: "KAVUN", m: "Sarı renkli, kokulu yaz meyvesi."},
{a: "HEYKEL", m: "Taş veya metalden yapılan sanat eseri."},
{a: "İSKELE", m: "Gemilerin yanaştığı platform."},
{a: "BALERİN", m: "Bale yapan kadın sanatçı."},
{a: "FESLEĞEN", m: "Güzel kokulu bir bitki türü."},
{a: "ÇÖL", m: "Kumlarla kaplı, suyun çok az olduğu geniş alan."},
{a: "BUĞDAY", m: "Un yapılan temel tarım bitkisi."},
{a: "KALE", m: "Savunma amaçlı yapılmış sağlam yapı."},
{a: "HARİTA", m: "Yeryüzünün kağıt üzerindeki çizimi."},
{a: "ÇEKİÇ", m: "Çivi çakmaya yarayan el aleti."},
{a: "ASTRONOT", m: "Uzay yolculuğu yapan eğitimli kişi."},
{a: "DOMATES", m: "Kırmızı, sulu ve çok tüketilen sebze."},
{a: "HOROZ", m: "Sabahları öten kümes hayvanı."},
{a: "MANTAR", m: "Toprakta yetişen, bazı türleri yenen bitki benzeri canlı."},
{a: "ÇİFTLİK", m: "Tarım ve hayvancılık yapılan arazi."},
{a: "KAPTAN", m: "Gemi veya uçağı yöneten kişi."},
{a: "DİNAMİT", m: "Patlayıcı madde."},
{a: "KUMBARA", m: "Para biriktirmek için kullanılan kutu."},
{a: "ÇELİK", m: "Demir ve karbon karışımı çok sert metal."},
{a: "FİLDİŞİ", m: "Filin uzun dişlerinden elde edilen değerli madde."},
{a: "AKVARYUM", m: "Balıkların içinde yaşadığı cam su kabı."},
{a: "HAVUÇ", m: "Turuncu renkli, tavşanların sevdiği sebze."},
{a: "DEĞİRMEN", m: "Tahıl öğüten veya enerji üreten yapı."},
{a: "ÇİNGENE", m: "Göçebe yaşam süren bir halk."},
{a: "FLÜT", m: "Üflemeli bir çalgı."},
{a: "CAMEKAN", m: "Dükkanların önündeki sergileme camı."},
{a: "ESKİMO", m: "Kutuplarda yaşayan yerli halk."},
{a: "ÇİZME", m: "Dize kadar çıkan koruyucu ayakkabı."},
{a: "ATLANTİK", m: "Dünyanın ikinci büyük okyanusu."},
{a: "GURUR", m: "Övünç duyma, onur."},
{a: "KOSTÜM", m: "Özel günlerde giyilen taklit kıyafeti."},
{a: "KAYIK", m: "Küçük deniz taşıtı."},
{a: "DÜNYA", m: "Üzerinde yaşadığımız gezegen."},
{a: "GAZETE", m: "Günlük haberleri veren basılı yayın."},
{a: "ARMADİLLO", m: "Vücudu sert bir kabukla kaplı olan memeli."},
{a: "CAN YELEĞİ", m: "Suda batmamayı sağlayan kıyafet."},
{a: "MERCEK", m: "Işığı kırarak görüntü büyüten cam."},
{a: "KÖMÜR", m: "Yeraltından çıkarılan siyah yanıcı maden."},
{a: "BASTON", m: "Yürürken destek alınan sopa."},
{a: "KUZU", m: "Koyunun yavrusu."},
{a: "HİPOPOTAM", m: "Su aygırı."},
{a: "KULE", m: "Çok yüksek ve ince yapı."},
{a: "GÜVERCİN", m: "Barışın simgesi olarak bilinen kuş."},
{a: "FINDIK", m: "Sert kabuklu küçük ve yuvarlak yemiş."},
{a: "BUZPATENİ", m: "Buz üzerinde kaymaya yarayan özel ayakkabı."},
{a: "BAYKUŞ", m: "Gece avlanan, başı çok dönebilen kuş."},
{a: "BEKÇİ", m: "Bir yeri korumakla görevli kişi."},
{a: "DEMİRYOLU", m: "Trenlerin üzerinde gittiği raylı yol."},
{a: "FİSKE", m: "Parmak ucuyla yapılan hafif vuruş."},
{a: "KAMYON", m: "Ağır yük taşıyan büyük araç."},
{a: "KAPLUMBAĞA", m: "Evini sırtında taşıyan yavaş hayvan."} 
];
